version: '3'

services:
  nginx:
    build:
      context: ./containers/nginx
    ports:
      - ${HTTP_PORT}:80
    volumes:
      - ./containers/nginx:/etc/nginx
      - proxy_log:/var/logs/nginx
    restart: always
    depends_on:
      - client
      - api

  client:
    build:
      context: ./containers/client
    ports:
      - ${CLIENT_PORT}:3000
    volumes:
      - ./containers/client:/usr/src/examin/client:cached
    tty: true
    stdin_open: true
    command: yarn start -p 3000 -b '0.0.0.0'

  api:
    build:
      context: ./containers/api
    ports:
      - ${API_PORT}:3000
    volumes:
      - ./containers/api:/usr/src/examin/api:cached
    tty: true
    stdin_open: true
    env_file:
      - ./env/api.env
    command: bundle exec rails server -p 3000 -b '0.0.0.0' -e development
    depends_on:
      - db

  db:
    build:
      context: ./containers/db
    ports:
      - ${DB_PORT}:3306
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: examin
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"

volumes:
  proxy_log: {}
  db_data: {}
