version: '3'

services:
  nginx:
    build:
      context: ./containers/nginx
    ports:
      - ${HTTP_PORT}:80
    volumes:
      - ./containers/nginx:/etc/nginx/conf.d
    restart: always
    depends_on:
      - client
      - api

  client:
    build:
      context: ./containers/client
    ports:
      - ${CLIENT_PORT}:3000
    restart: always
    depends_on:
      - api

  api:
    build:
      context: ./containers/api
      dockerfile: Dockerfile_production
    ports:
      - ${API_PORT}:3000
    env_file:
      - ./env/api.env
    restart: always
    depends_on:
      - db

  db:
    build:
      context: ./containers/db
    ports:
      - ${DB_PORT}:3306
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: examin
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"

volumes:
  db_data: {}
