version: '3'

services:
  nginx:
    build:
      context: ./containers/nginx
    ports:
      - 80:80
    volumes:
      - ./containers/nginx:/etc/nginx/conf.d
    restart: always
    depends_on:
      - client

  client:
    build:
      context: ./containers/client/docker
    ports:
      - 3000:3000
    volumes:
      - ./containers/client:/usr/src/examin/client:cached
    tty: true
    stdin_open: true
    environment:
      BASE_URL: http://api:3000
    command: yarn start -p 3000 -b '0.0.0.0'
    depends_on:
      - api

  api:
    build:
      context: ./containers/api
    ports:
      - 3500:3000
    volumes:
      - ./containers/api:/usr/src/examin/api:cached
    tty: true
    stdin_open: true
    environment:
      RAILS_ENV: production
    command: bundle exec rails server -p 3000 -b '0.0.0.0'
    depends_on:
      - db

  db:
    build:
      context: ./containers/db
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: examin
      MYSQL_USER: examin
      MYSQL_PASSWORD: examin

volumes:
  db_data: {}
